FROM ubuntu
RUN apt-get update
RUN apt-get install python3 -y
RUN apt-get install python3-pip -y
#ADD export PATH="$PATH:/usr/bin/python3"
RUN pip install flask
RUN pip install Pillow
RUN pip install reportlab
RUN pip install flask_cors
# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
#ADD . /app
COPY . .
# Install any needed packages specified in requirements.txt
# Make port 5000 available to the world outside this container
EXPOSE 5000

#CMD ["flask","--app","app", "run","--host=0.0.0.0 "]
        #CMD ["flask","run","--host","0.0.0.0"]


#CMD ["flask","run","--host","0.0.0.0","ssl_context=adhoc"]

CMD ["flask", "run", "--host", "0.0.0.0","--cert", "adhoc"]